services:
  app:
    build:
      target: prod
      args:
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    environment:
      NODE_ENV: production
    command: sh -c "npx prisma migrate deploy && node server.js"
