services:
  app:
    build:
      target: prod
      args:
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    environment:
      NODE_ENV: production
      AUTH_TRUST_HOST: "true"
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    command: sh -c "node node_modules/prisma/build/index.js migrate deploy && node server.js"
