services:
  app:
    build:
      target: dev
    environment:
      WATCHPACK_POLLING: "true"
      NEXTAUTH_URL: http://localhost:7190
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "node node_modules/prisma/build/index.js migrate deploy && node node_modules/prisma/build/index.js generate && npm run dev"
